version: '2'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - web-db:/var/lib/mysql
volumes:
  web-db:
